---
- hosts: all
  become: yes
  tasks:
          - name: add ssh key to user
            user:
                    name: paras031
                    generate_ssh_key: yes
                    ssh_key_bits: 2048
                    ssh_key_file: .ssh/id_rsa
                    

